### Login User
#POST http://localhost:8080/api/auth/login
POST https://api-generator-cv.onrender.com/api/auth/login
Content-Type: application/json

{
  "username" : "feals",
  "password" : "Jakarta2001!@"
}

> {% client.global.set("auth_token", response.body.data.token); %}

### Logout
DELETE https://api-generator-cv.onrender.com/api/auth/logout
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{}

### Register User
POST https://api-generator-cv.onrender.com/api/users
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
  "username" : "feals",
  "password" : "Jakarta2001!@",
  "email" : "febyalexsatria@gmail.com"
}

### Get User
GET https://api-generator-cv.onrender.com/api/users/current
Content-Type: application/json
X-API-TOKEN: {{auth_token}}

{}

### Create detail user
POST https://localhost:8080/api/user/detail
#POST https://api-generator-cv.onrender.com/api/user/detail
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
  "firstName" : "Febyk",
  "lastName" : "Alek Satria",
  "city" : "Jakarta",
  "country" : "Indonesia",
  "phone" : "081373107544",
  "about" : "saya programmer"
}

### Get detail user
GET  http://localhost:8080/api/user/detail
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
}

### Update detail user
PUT https://api-generator-cv.onrender.com/api/user/detail
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
  "firstName" : "Febyk",
  "lastName" : "Alek Satria",
  "city" : "Jakarta",
  "country" : "Indonesia",
  "phone" : "081373107544",
  "about" : "programmer"
}

### Get social media
GET https://api-generator-cv.onrender.com/api/socials
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
}

### Create social media
POST https://api-generator-cv.onrender.com/api/socials
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "platform" : "instagram",
    "username" : "febyk.as"
  }
]

###Update social media
PUT https://api-generator-cv.onrender.com/api/socials
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
{
  "id" : "bd1ab19c-0bb0-4a50-8c69-70c8bd3ea48a",
  "platform" : "instagram",
  "username" : "febyk.as",
  "url" : "https://www.instagram.com/febyk.as/"
}
]

###Delete social media
DELETE https://api-generator-cv.onrender.com/api/socials/c44913c8-9daa-4a72-8e23-ad50231346df
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{

}

### Get skill
GET https://api-generator-cv.onrender.com/api/skills
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
}

### Create skill
POST https://api-generator-cv.onrender.com/api/skills
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "skill" : "React/Next Js",
    "level" : "advanced"
  },
  {
    "skill" : "Node Js",
    "level" : "advanced"
  },
  {
    "skill" : "Laravel",
    "level" : "advanced"
  },
  {
    "skill" : "Flutter",
    "level" : "advanced"
  },
  {
    "skill" : "Springboot",
    "level" : "advanced"
  }
]

### Update skill
PUT https://api-generator-cv.onrender.com/api/skills
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "id" : "f3b5df55-cc63-42ae-9e5a-27360bef62f6",
    "skill" : "game",
    "level" : "menengah"
  },
  {
    "id" : "325cfb6c-a96b-45bb-b757-425ee997d004",
    "skill" : "programmer",
    "level" : "jago"
  }
]

### Delete skill
DELETE https://api-generator-cv.onrender.com/api/skills/f3b5df55-cc63-42ae-9e5a-27360bef62f6
Content-Type: application/json
X-API-TOKEN:{{auth_token}}



### Get achieve
GET https://api-generator-cv.onrender.com/api/achieves
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
}

### Create achieve
POST https://api-generator-cv.onrender.com/api/achieves
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "achieve" : "balap karung",
    "year" : "1999"
  },
  {
    "achieve" : "makan kerupuk",
    "year" : "2022"
  }
]

### Update achieve
PUT https://api-generator-cv.onrender.com/api/achieves
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "id" : "e65d669e-ef24-4bc1-8e07-1af127cc1d14",
    "achieve" : "balap sepeda",
    "year" : "2004"
  }
]

### Delete achieve
DELETE https://api-generator-cv.onrender.com/api/achieves/e65d669e-ef24-4bc1-8e07-1af127cc1d14
Content-Type: application/json
X-API-TOKEN:{{auth_token}}



### Get language
GET https://api-generator-cv.onrender.com/api/languages
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
}

### Create language
POST https://api-generator-cv.onrender.com/api/languages
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "language" : "Indonesia",
    "level" : "active"
  },
  {
    "language" : "makan kerupuk",
    "level" : "passive"
  }
]

### Update language
PUT https://api-generator-cv.onrender.com/api/languages
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "id" : "98dc8f5a-24d2-4bb5-a8e0-07f6f8b63ea3",
    "language" : "English",
    "level" : "passive"
  }
]

### Delete language
DELETE https://api-generator-cv.onrender.com/api/languages/21759f89-c7f4-4dd4-9cb2-d43c2f89e17f
Content-Type: application/json
X-API-TOKEN:{{auth_token}}



### Get education
GET https://api-generator-cv.onrender.com/api/educations
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
}

### Create education
POST https://api-generator-cv.onrender.com/api/educations
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "school" : "Sriwijaya University",
    "startDate" : "2018-08-01",
    "endDate" : "2022-07-01",
    "major" : "Teknik Informatika",
    "gpa" : 3.62,
    "desc" : "Kuliah"
  },
  {
    "school" : "SMA N 1",
    "startDate" : "2015-07-01",
    "endDate" : "2018-04-01",
    "major" : "MIPA",
    "gpa" : 90,
    "desc" : "Sekolah"
  }
]

### Update education
PUT https://api-generator-cv.onrender.com/api/educations
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "id" : "e15018b3-e3ba-4f04-b4a5-37e065441b5d",
    "school" : "SMA N 1",
    "startDate" : "2015-04-11",
    "endDate" : "2018-04-11",
    "major" : "MIPA",
    "gpa" : 92,
    "desc" : "Sekolah"
  }
]

### Delete education
DELETE https://api-generator-cv.onrender.com/api/educations/e15018b3-e3ba-4f04-b4a5-37e065441b5d
Content-Type: application/json
X-API-TOKEN:{{auth_token}}




### Get organization
GET https://api-generator-cv.onrender.com/api/organizations
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
}

### Create organization
POST https://api-generator-cv.onrender.com/api/organizations
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "organization" : "Uread",
    "startDate" : "2018-04-11",
    "endDate" : "2022-04-11",
    "title" : "Sekretaris manajer",
    "desc" : "organisasi"
  },
  {
    "organization" : "HMIF",
    "startDate" : "2015-04-11",
    "endDate" : "2018-04-11",
    "title" : "Deputy Division Head Kajian Strategi",
    "desc" : "himpunan"
  }
]

### Update organization
PUT https://api-generator-cv.onrender.com/api/organizations
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "id" : "1bd49438-2ab5-4d62-973b-7b0f5151e57e",
    "organization" : "HMIF",
    "startDate" : "2015-04-11",
    "endDate" : "2018-04-11",
    "title" : "WAKADIV Kastrad",
    "desc" : "himpunan"
  }
]

### Delete organization
DELETE https://api-generator-cv.onrender.com/api/organizations/1bd49438-2ab5-4d62-973b-7b0f5151e57e
Content-Type: application/json
X-API-TOKEN:{{auth_token}}



### Get experience
GET https://api-generator-cv.onrender.com/api/experiences
Content-Type: application/json
X-API-TOKEN:{{auth_token}}
{
}

### Create experience
POST https://api-generator-cv.onrender.com/api/experiences
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "company" : "KISEL Group",
    "startDate" : "2018-04-11",
    "endDate" : "2022-04-11",
    "title" : "STAFF",
    "desc" : "Staff Developer"
  },
  {
    "company" : "HANA Bank",
    "startDate" : "2015-04-11",
    "endDate" : "2018-04-11",
    "title" : "Asisten Manager Service Interface",
    "desc" : "ASMEN Interface"
  }
]

### Update experience
PUT https://api-generator-cv.onrender.com/api/experiences
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

[
  {
    "id" : "7e6b5b54-b1af-450e-bb79-91e41dd993ec",
    "company" : "KISEL Group",
    "startDate" : "2018-04-11",
    "endDate" : "2022-04-11",
    "title" : "STAFF",
    "desc" : "Staff Developer"
  }
]

### Delete experience
DELETE https://api-generator-cv.onrender.com/api/experiences/7e6b5b54-b1af-450e-bb79-91e41dd993ec
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

### DOwnload PDF
POST http://localhost:8080/download/pdf
Content-Type: application/json
X-API-TOKEN:{{auth_token}}

{
  "firstName": "Febyk",
  "lastName": "Alek Satria",
  "city": "Jakarta",
  "country": "Indonesia",
  "about": "programmer",
  "phone": "081373107544"
}











